tasks:
  - init: |
      for d in */ ; do
        npm i
      done
    command: |
      echo "Loading"
      sleep 1
      clear && echo "Loading."
      sleep 1
      clear && echo "Loading.."
      sleep 1
      clear && echo "Loading..."
      sleep 1
      clear && echo "Loading.."
      sleep 1
      clear && echo "Loading."
      sleep 1
      clear && echo "Loading.."
      sleep 1
      clear && echo "Loading..."
      sleep 1
      clear && echo "Loading.."
      sleep 1
      clear && echo "Loading."
      sleep 1
      clear && echo "Loading"
      sleep 1
      clear && echo "Loading."
      sleep 1
      clear && echo "Loading.."
      sleep 1
      clear && echo "Loading..."
      sleep 1
      clear && echo "Loading.."
      sleep 1
      clear && echo "Loading."
      sleep 1
      clear && echo "Loading"
      sleep 1
      clear
      echo "Hey!"
      echo "Just ignore me.."
      echo "I'm just here to run commands for you."
      sleep 4
      clear
      echo "I'll run fish"
      sleep 1
      clear && echo "I'll run fish."
      sleep 1
      clear && echo "I'll run fish.."
      sleep 1
      clear && echo "I'll run fish..."
      sleep 1
      clear
      echo "Here ya go!"
      fish

image:
  file: Dockerfile
